name: "Knative Client Service"
description: "Creating Knative Services using kn"
branding:
  icon: book-open
  color: yellow
inputs:
  k8s_api_server_url:
    description: 'The Kube API Server URL'
    required: true
  openshift_token:
    description: 'The OpenShift Login Token'
    required: false
  openshift_user:
    description: 'The OpenShift Login User'
    required: false
  openshift_password:
    description: 'The OpenShift Login User Password'
    required: false
  service_name:
    description: "The Knative Service Name"
    required: true
  service_namespace:
    description: "The Kubernetes Namespace to deploy to "
    required: false
    default: "default"
  service_operation:
    description: 'The Knative Service Operation'
    required: false
    default: "create"
  container_image:
    description: 'The Knative Serivce Image'
    required: true
  service_params:
    description: 'The extra parameter to pass to service'
    required: false
outputs:
  service_url:
    description: "The Knative Service URL"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.k8s_api_server_url }}
     - ${{ inputs.openshift_token }}
     - ${{ inputs.openshift_user }}
     - ${{ inputs.openshift_password }}
     - ${{ inputs.service_name }}
     - ${{ inputs.service_namespace }}
     - ${{ inputs.service_operation }}
     - ${{ inputs.container_image }}
     - ${{ inputs.service_params }}