name: CI

on:
  push:
    branches:
      - "master"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v2
      - name: Build the Action Image
        id: buildah_build
        uses: redhat-actions/buildah-build@v1
        with:
           push: false
           image: ghcr.io/kameshsampath/kn-service-action
           dockerfiles: |
             ./Dockerfile
           tags: v0
      - uses: GoogleCloudPlatform/release-please-action@v2.7.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
